services:
  debisim2p5:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        CUDA_VERSION: ${CUDA_VERSION:-12.8.1}
    image: fly0ut/debisim2p5:${CUDA_TAG:-cuda12.8.1}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    volumes:
      - ../results:/app/results
      - ../examples/stl_pools:/app/examples/stl_pools:ro

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}

    command: >
      --config configs/config_calibration_phantom_dect.py
      --sim_dir results/calibration_phantom/
      --num_bags 1
